### ISSUE TITLE
Spyder returning TypeError after updating it to 4.1.5

### ISSUE THREAD

**Issue by duttashi** [duttashi/learnpy#45]
> This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:

> An exception has occurred, use %tb to see the full traceback.
> TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

**Comment by duttashi** [comment]
**solution**

- Launch command prompt and navigate to the python installation. In my case its in `c:\users\username\miniconda3`
- Execute the following commands in following order

> pip uninstall spyder
> conda uninstall spyder
> conda install spyder

Reference: See this [SO post](https://stackoverflow.com/questions/63739215/spyder-returning-typeerror-after-updating-to-spyder-4-1-4) answer by user `CrossEntropy`
